project_defaults: &defaults
  docker:
      - image: circleci/python:3.7.2
        environment:
          CC_TEST_REPORTER_ID: ${CC_TEST_REPORTER_ID}
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test

      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

  working_directory: ~/ridemyway-api-django

cmd_install_dependecies: &cmd_install_dependecies
  run:
    name: Install dependecies
    command: |
      sudo pip install -r requirements.txt

cmd_download_cc_test_reporter: &cmd_download_cc_test_reporter
  run:
    name:  Download cc-test-reporter
    command: |
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter

cmd_attach_workspace: &cmd_attach_workspace
  attach_workspace:
    at: ridemyway-api-django/

cmd_persist_workspace: &cmd_persist_workspace
  persist_to_workspace:
    root: .
    paths: .

# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:

  run_tests_and_upload_coverage:
    <<: *defaults
    steps:
      - checkout
      - *cmd_install_dependecies
      - *cmd_attach_workspace
      - *cmd_download_cc_test_reporter

      - run:
          name: Run tests
          command: |
            pytest --cov=ridemyway/tests --cov-report xml
            ./cc-test-reporter format-coverage coverage.xml -t "coverage.py" -o "./cc.testreport.json"
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./cc-test-reporter upload-coverage -i ./cc.testreport.json

workflows:
  version: 2
  test_and_upload_coverage:
    jobs:
      - run_tests_and_upload_coverage
