# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    working_directory: ~/ridemyway-api-django

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - api-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - api-dependencies-

      - run:
          name: Install dependencies
          command: |
            curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            pyenv install 3.7.2 -s
            pyenv local 3.7.2
            pip3 install --user pipenv==2018.5.18
            python3 -m pip install pipenv==2018.5.18
            python3 -m pipenv install

      - save_cache:
          key: api-dependencies-{{ checksum "Pipfile.lock" }}
          paths:
            - $(python3 -m pipenv --venv)

      # run tests!
      - run:
          name: Run tests
          command: |
            source $(python3 -m pipenv --venv)/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
